name: 'Takako Ainsworth, LCSW'
favicon: null
layout_spectrum: 0.48386120912618935
typography_spectrum: 0.03051012847572565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.08993792743422091
  lightness: 0.5419069288764149
  saturation: 0.4931865092366934
  rhythmicContrast: 0.17224418581463397
purpose: []
