name: 'Takako Ainsworth, LCSW'
favicon: null
layout_spectrum: 0.72887
typography_spectrum: 0.50213
title: Life in Harmony
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#24bbdb'
    - '#c7c3c4'
    - '#1b92e3'
    - '#c99d3e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
